import { Card, CardContent } from "@/components/ui/card"
import { getCurrentSession } from "@/lib/auth-utils"
import { redirect } from "next/navigation"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import MarkdownRenderer from "@/components/admin/MarkdownRenderer"

export default async function FactoryShareLibraryDocPage() {
    const session = await getCurrentSession()

    if (!session?.user?.id || session.user.role !== "ADMIN") {
        redirect("/login")
    }

    const content = `
# 📤 分享库集成指南

## 📖 概述

**ShareResult** 是一个通用的分享组件，旨在为所有工具提供统一的**结果分享**和**截图下载**功能。它无缝集成到现有的工厂模式中，只需几行代码即可为你的工具添加社交推广能力。

### 核心功能

- 📸 **自动截图**：将指定区域（如生成结果）自动转换为图片并下载。
- 🔗 **社交分享**：一键分享到 Twitter, Facebook, LinkedIn。
- 📋 **复制链接**：快速复制当前工具页面的链接。
- 🎨 **高度定制**：支持自定义标题、分享文案和样式。

---

## 🚀 如何使用

### 1. 引入组件

在你的工具组件文件（例如 \`components/tools/YourTool.tsx\`）中引入 \`ShareResult\` 和 \`useRef\`。

\`\`\`typescript
import { useRef } from "react"
import { ShareResult } from "@/components/tools/ShareResult"
\`\`\`

### 2. 创建引用 (Ref)

创建一个 \`ref\` 指向你想要截图的 DOM 元素。通常是包含生成结果的容器。

\`\`\`typescript
export default function YourTool({ result }: { result: string }) {
  // 创建 ref
  const resultRef = useRef<HTMLDivElement>(null)

  return (
    <div>
      {/* 将 ref 绑定到结果容器 */}
      <div ref={resultRef} className="p-6 bg-white rounded-xl border">
        <h2 className="text-xl font-bold mb-4">生成结果</h2>
        <div className="prose">{result}</div>
        
        {/* 在结果底部添加水印或品牌标识 (可选) */}
        <div className="mt-4 text-sm text-gray-400">
          Generated by AI Website Tools
        </div>
      </div>

      {/* 3. 添加 ShareResult 组件 */}
      <ShareResult 
        contentRef={resultRef}       // 必填：绑定 ref
        title="my-awesome-result"    // 选填：下载文件名
        shareText="我刚刚用这个AI工具生成了超棒的内容！" // 选填：分享文案
      />
    </div>
  )
}
\`\`\`

---

## ⚙️ 参数说明 (Props)

| 参数名 | 类型 | 必填 | 默认值 | 说明 |
|Data | Type | Required | Default | Description |
|---|---|---|---|---|
| \`contentRef\` | \`RefObject<HTMLElement>\` | ✅ 是 | - | 指向要截图的 DOM 元素 |
| \`title\` | \`string\` | ❌ 否 | "ai-tool-result" | 下载图片的文件名前缀 |
| \`shareText\` | \`string\` | ❌ 否 | (默认文案) | 社交媒体分享时的预填文字 |
| \`shareUrl\` | \`string\` | ❌ 否 | 当前页面 URL | 分享的链接地址 |
| \`className\` | \`string\` | ❌ 否 | - | 自定义组件外层样式 |

---

## 💡 最佳实践

1. **包含品牌标识**：建议在 \`contentRef\` 包裹的区域内添加网站 Logo 或名称，这样用户下载图片分享时能起到推广作用。
2. **样式隔离**：\`ShareResult\` 组件默认有上边距和虚线边框，适合放在结果区域的下方。
3. **深色模式**：截图功能支持深色模式，但建议在结果容器上显式设置背景色（如 \`bg-background\` 或 \`bg-white\`），以确保生成的图片背景正确。

---

## 示例代码

查看 \`components/tools/ShareResult.tsx\` 了解源码实现。
`

    return (
        <div>
            <div className="flex items-center justify-between mb-8">
                <div>
                    <h1 className="text-3xl font-bold">📤 分享库集成指南</h1>
                    <p className="text-muted-foreground">为工具添加截图下载与社交分享功能</p>
                </div>
                <Link href="/admin/docs">
                    <Button variant="outline">← 返回文档列表</Button>
                </Link>
            </div>

            <Card>
                <CardContent className="pt-6">
                    <MarkdownRenderer content={content} />
                </CardContent>
            </Card>
        </div>
    )
}
